#!/bin/bash
echo -e "\tarr-size\tNonSIMDMM\tSIMDMM\tSpeedup\tNonSIMDSumMM\tSIMDSumMM\tSumSpeedup"
for n in 1024 1048576 2097152 4194304 8388608
do
    g++ all04.cpp -DARRAYSIZE=$n -o proj4 -fopenmp
    ./proj4
done
